### ISSUE TITLE
disallows

### ISSUE THREAD

**Issue by DemetriusStorm** [gabrielbarker/qual-id#54]
Do you have problems with value gap processing? I think it's wrong to exclude spaces in the names of brands or music directions or any other values. Am I wrong? Please correct me. [LINK](https://github.com/gabrielbarker/qual-id/blob/fc159c3da4834077f310c73c103cfec43549796c/test/utils/category_helper.py#L2)

**Comment by gabrielbarker** [comment]
It's just a design choice. For this use case I don't think it's very useful to have spaces and separators. Say I'm naming bug reports using qual IDs rather than just IDs, I don't think having one as `michigan-strawberry`, and then another as `new york-raspberry`. I feel like it is simpler to just stick to single words 🙂

**Comment by DemetriusStorm** [comment]
@gabrielbarker I think you right. Close this issue please :)
